### ISSUE TITLE
Proposol to move project to jazzband

### ISSUE THREAD

**Issue by nikolas** [rtfd/CommonMark-py#136]
I would like to move this project to the [Jazzband](https://jazzband.co/) organization to ensure that it continues to receive admin and maintenance support if I or any of the readthedocs admins aren't around. Jazzband already maintains a bunch of libraries similar to CommonMark-py: https://github.com/jazzband

@ericholscher @agjohnson does this sound like a good idea?

**Comment by ericholscher** [comment]
Seems like a neat idea. I'm definitely not keeping up w/ this repo as much as I should be. I'm not 100% sure if Jazzband would be beneficial, but if it would allow things to be better maintained, I'm +1 on it.

**Comment by agjohnson** [comment]
I'm probably +0, I don't see a huge benefit to moving ownership of the repo. We're also happy to include anyone in a team here to give commit/admin access.

My only reservation is where commonmark-py deviates and breaks backwards compatibility with recommonmark -- I don't know the intent of Jazzband or how invested they are in recommonmark. We should have a document that outlines what supporting recommonmark looks like, and if there is anything we can do to automate not breaking recommonmark, that might be another mechanism to add. For some of our interdependent projects, we add the dependency testing to CI.

**Comment by nikolas** [comment]
Alright, given the lukewarm response I'll close this. I suppose there aren't any major reasons not to keep this project under rtfd.
