### ISSUE TITLE
Nested list in markdown cannot convert to rst correctly

### ISSUE THREAD

**Issue by flynxea** [rtfd/CommonMark-py#269]
```
* abc
    - 123
    - 456
* def
```
should show as:
* abc
    - 123
    - 456
* def

But with the code:
```python
def md2rst(lines):
    m = '\n'.join(lines)

    parser = commonmark.Parser()
    ast = parser.parse(m)

    renderer = commonmark.ReStructuredTextRenderer()
    rst = renderer.render(ast)

    lines[:] = rst.splitlines()
```
it cannot output the correct rst string.

**Comment by Toliak** [comment]
The same issue.
Sometimes `node.list_data['marker_offset']` contains invalid offset number, so, that's **parsing to AST** issue.

Example:
![image](https://user-images.githubusercontent.com/25643405/116994687-b63cf780-ace1-11eb-9ce4-0b9502b56508.png)
