### ISSUE TITLE
0.5.5 release

### ISSUE THREAD

**Issue by nikolas** [rtfd/CommonMark-py#29]
In order to stay organized, and allow people to use our new code, which will help with stability, let's make a 0.5.5 release tagged at the commit where I incremented the version number here: https://github.com/rtfd/CommonMark-py/pull/16

I don't have permission to do this: https://github.com/rtfd/CommonMark-py/releases

**Comment by ericholscher** [comment]
Released. Thanks for the reminder.

**Comment by nikolas** [comment]
Thank you. I think we should also make a wheel file of this version and attach it to the release. I can make it and send it to you if necessary.

**Comment by ericholscher** [comment]
I'd like to release it to PyPi when we get the proper keys there -- I think
a GitHub release isn't really going to be widely used, and still seems
unofficial until we push to PyPi.

On Fri, Dec 18, 2015 at 12:29 PM, Nik Nyby <notifications@github.com> wrote:

> Thank you. I think we should also make a wheel file of this version and
> attach it to the release. I can make it and send it to you if necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/CommonMark-py/issues/29#issuecomment-165891530>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
@nikolas You should also have push access on the repo now -- so you can upload it if you want. :fireworks:

**Comment by nikolas** [comment]
Cool thanks a lot.

Yeah, I guess having a wheel file on github is not so important since it's not like many people are using this until it's on pypi. I just wanted us to be able to refer to version numbers when debugging stuff during development, and use the new versions on my django projects to test them, but I can just make my own wheel files.

**Comment by nikolas** [comment]
This is on pypi now https://pypi.python.org/pypi/CommonMark/0.5.5

**Comment by ericholscher** [comment]
:+1:
