### ISSUE TITLE
Package name is not PEP 8 compliant

### ISSUE THREAD

**Issue by pydsigner** [rtfd/CommonMark-py#60]
I realize that there are already many users of the package, but is there any possibility of the package's name being made to be PEP 8 compliant (and also match the js version)? It's a small issue but I'd much rather be looking at `import commonmark` than `import CommonMark` in my code.

**Comment by lu-zero** [comment]
Probably we could provide CommonMark as alias for the time being and the second next major version drop it.

Willing to send over a patch for it? =)

**Comment by ericholscher** [comment]
Should be pretty easy to do `import CommonMark as commonmark`, we could
also ship with the lower-case alias in the core distro. I wouldn't be
opposed to a PR that did this.

On Tue, Apr 5, 2016 at 9:54 AM, Daniel Foerster <notifications@github.com>
wrote:

> I realize that there are already many users of the package, but is there
> any possibility of the package's name being made to be PEP 8 compliant (and
> also match the js version)? It's a small issue but I'd much rather be
> looking at import commonmark than import CommonMark in my code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/CommonMark-py/issues/60>
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by pydsigner** [comment]
I'll try to get a PR prepared tonight.

**Comment by nikolas** [comment]
I would also prefer `commonmark` over `CommonMark`! Thanks for bringing this up.

**Comment by nikolas** [comment]
Also maybe worth noting that this repository could also be renamed to something like commonmark.py.

**Comment by nikolas** [comment]
@pydsigner have you made any progress with this? To me it seems like a difficult problem to fix without making a new package. Also, when I navigate to https://pypi.python.org/pypi/commonmark it redirects me to https://pypi.python.org/pypi/CommonMark. It would be nice to change that as well but I don't know how.

**Comment by pydsigner** [comment]
@nikolas I unfortunately have been a bit busier than hoped, but I do have a plan of how to do this.

**Comment by nikolas** [comment]
Maybe this is just a matter of changing the `name` in `setup.py` from CommonMark to commonmark. And we would also want to move the `CommonMark` directory to `commonmark`. Of course, I would hate to break everyone's existing imports. Our readme directs users to `import CommonMark`.

**Comment by nikolas** [comment]
Alright, it looks like just renaming the `CommonMark` directory to `commonmark`, and changing all the imports solves this problem.

I've also symlinked `CommonMark` to `commonmark` for now, for compatibility.  I've opened a pull request here: https://github.com/rtfd/CommonMark-py/pull/131
