### ISSUE TITLE
Detach fork from parent repo to make this repo searchable

### ISSUE THREAD

**Issue by dhensen** [rtfd/CommonMark-py#94]
I noticed when trying to search in the code of this repo the following error message:

> Sorry, forked repositories are not currently searchable.
> You could try searching the parent repository.

Is it an option to detach from the parent repo in order to be able to search in the code of this repo on github?

**Comment by nikolas** [comment]
No, it's not an option that I'm aware of, but correct me if I'm wrong.

**Comment by dhensen** [comment]
It's indeed not an option in the github settings UI. But I know that one can ask Github support and they will do it for you if you want them to.

**Comment by nikolas** [comment]
Ah, I think this may be because I'm not necessarily and "admin" of this repo (I don't have a Settings tab available), I just have commit privileges as a developer. Maybe @ericholscher can take a look and address this.

**Comment by ericholscher** [comment]
Hmm. I'm fine detaching the fork, but it sounds like we need to email github?

**Comment by nikolas** [comment]
@ericholscher yes, contacting GitHub support sounds like the way to do it: https://stackoverflow.com/a/16052845/173630

I'll let you handle this since I don't have admin privileges here.

**Comment by jonathan-s** [comment]
In my experience they are fairly quick in handling issues like this. Has an email been sent?

**Comment by nikolas** [comment]
I'm not sure if @ericholscher has sent the email yet. Eric - if you don't have time to manage this I'm happy to do it if you'd like to give me admin access to this repo.

**Comment by ericholscher** [comment]
I've emailed them 👍

**Comment by nikolas** [comment]
I haven't seen any changes, so I just opened a support request on GitHub for this.

**Comment by nikolas** [comment]
@ericholscher GitHub needs permission to do this from someone with admin permissions on this repo:

> Can you please cc the appropriate person into this thread and ask that they 'reply all' from a verified email address on their GitHub account with something like "I grant permission to detach rtfd/CommonMark-py from rolandshoemaker/CommonMark-py."

**Comment by ericholscher** [comment]
I don't see the email that I'm meant to respond to?

**Comment by ericholscher** [comment]
Ah, just got it :)

**Comment by nikolas** [comment]
Alright, it looks like GitHub's completed this.
